cmake_minimum_required(VERSION 3.16)
set(PROJECT_NAME LayaNative3.0)
project(${PROJECT_NAME})
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(LINUX TRUE)
else()
    set(LINUX FALSE)
endif()

set(CONCH_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${CONCH_ROOT_DIR}/cmake/preprocessor.cmake)

option(USE_JS_V8_DEBUGGER "Use v8 debugger" ON)
option(USE_DOUBLE_PRECISION "Use double" OFF)

if(USE_JS_V8_DEBUGGER)
	if(ANDROID OR MSVC OR LINUX)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DJS_V8_DEBUGGER")
	endif()
endif()

if(USE_DOUBLE_PRECISION)
	add_definitions(-DUSE_DOUBLE_PRECISION)
endif()

if(ANDROID)
	add_definitions(-DJS_V8)
	#add_definitions(-DWEBGL_THREAD)
	option(CONCH_USE_CURL_DOWNLOAD "Use CURL" OFF)
elseif(IOS)
	add_definitions(-DJS_V8)
	#add_definitions(-DWEBGL_THREAD)
	option(CONCH_USE_CURL_DOWNLOAD "Use CURL" OFF)
elseif(LINUX)
	add_definitions(-DJS_V8)
	#add_definitions(-DWEBGL_THREAD)
	add_definitions(-DLINUX)
	option(CONCH_USE_CURL_DOWNLOAD "Use CURL" ON)
elseif(MSVC)
	add_definitions(-DJS_V8)
	#add_definitions(-DWEBGL_THREAD)
	option(CONCH_USE_CURL_DOWNLOAD "Use CURL" ON)
endif()

if(CONCH_USE_CURL_DOWNLOAD)
	add_definitions(-DCURL_DOWNLOAD)
endif()

if(MSVC)
	# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W0 /Zc:__cplusplus")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG -std=c++17 -O0")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -std=c++17")
else()
	# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions -std=c++17")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG -std=c++17 -O0")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -std=c++17")
endif()

add_subdirectory(conch)
add_subdirectory(template)
add_subdirectory(modules/utils)
add_subdirectory(modules/binder)

if(MSVC OR LINUX)
	add_subdirectory(modules/app)
endif()
add_subdirectory(third_party/zlib zlib)
add_subdirectory(third_party/zip zip)
add_subdirectory(third_party/websockets websockets)
add_subdirectory(third_party/openssl openssl)
add_subdirectory(third_party/png png)
add_subdirectory(third_party/rapidxml rapidxml)
add_subdirectory(third_party/ghc ghc)
add_subdirectory(third_party/jpeg-turbo jpeg-turbo)
add_subdirectory(third_party/mpg123 mpg123)
add_subdirectory(third_party/openal openal)
add_subdirectory(third_party/ogg ogg)
add_subdirectory(third_party/freetype freetype)
add_subdirectory(third_party/curl curl)
add_subdirectory(third_party/v8 v8)
add_subdirectory(third_party/angle angle)
add_subdirectory(third_party/bullet bullet)
add_subdirectory(third_party/physx physx)
add_subdirectory(third_party/sdl sdl)
add_subdirectory(third_party/benchmark benchmark)

message("CMAKE_BUILD_TYPE:${CMAKE_BUILD_TYPE}")
message("CMAKE_C_FLAGS:${CMAKE_C_FLAGS}")
message("CMAKE_CXX_FLAGS:${CMAKE_CXX_FLAGS}")
message("CMAKE_C_FLAGS_RELEASE:${CMAKE_C_FLAGS_RELEASE}")
message("CMAKE_CXX_FLAGS_RELEASE:${CMAKE_CXX_FLAGS_RELEASE}")
message("CMAKE_C_FLAGS_DEBUG:${CMAKE_C_FLAGS_DEBUG}")
message("CMAKE_CXX_FLAGS_DEBUG:${CMAKE_CXX_FLAGS_DEBUG}")