cmake_minimum_required(VERSION 3.16)
set(PROJECT_NAME LayaNative3.0)
project(${PROJECT_NAME})
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)


set(CONCH_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${CONCH_ROOT_DIR}/cmake/preprocessor.cmake)


set(IOS_MINIMUM_DEPLOYMENTS_VERSION "12.0"  CACHE STRING " iOS minimum deployments version" FORCE)

option(CONCH_USE_DCC "Use NEW DCC" ON)

if(OS_OHOS)
	option(TRACY_PROFILER_ENABLED "Profiler enabled" OFF) 
else()
	option(TRACY_PROFILER_ENABLED "Profiler enabled" OFF) 	
endif()

if(OS_ANDROID)
	option(CONCH_USE_SWAPPY "Use Swappy" ON)
else()
	option(CONCH_USE_SWAPPY "Use Swappy" OFF)
endif()
if(OS_ANDROID)
	option(CONCH_USE_CURL_DOWNLOAD "Use NEW CURL" OFF)
	option(CONCH_USE_OLD_CURL_DOWNLOAD "Use CURL" OFF)
	option(USE_JS_V8_DEBUGGER "Use v8 debugger" ON)
	option(CONCH_USE_JPEG_XL "USE JPEG XL" OFF)
	option(USE_PHYSX "Use physx" ON)
	option(USE_JS_V8 "Use v8" ON)
elseif(OS_IOS)
	option(CONCH_USE_CURL_DOWNLOAD "Use NEW CURL" OFF)
	option(CONCH_USE_OLD_CURL_DOWNLOAD "Use CURL" OFF)
	option(USE_JS_V8_DEBUGGER "Use v8 debugger" ON)
	option(CONCH_USE_JPEG_XL "USE JPEG XL" OFF)
	option(USE_PHYSX "Use physx" ON)
	option(USE_JS_V8 "Use v8" ON)
elseif(OS_WINDOWS)
	option(CONCH_USE_CURL_DOWNLOAD "Use NEW CURL" OFF)
	option(CONCH_USE_OLD_CURL_DOWNLOAD "Use CURL" ON)
	option(USE_JS_V8_DEBUGGER "Use v8 debugger" ON)
	option(CONCH_USE_JPEG_XL "USE JPEG XL" ON)
	option(USE_PHYSX "Use physx" OFF)
	option(USE_JS_V8 "Use v8" ON)
elseif(OS_OHOS)
	option(CONCH_USE_CURL_DOWNLOAD "Use NEW CURL" OFF)
	option(CONCH_USE_OLD_CURL_DOWNLOAD "Use CURL" ON)
	option(USE_JS_V8_DEBUGGER "Use v8 debugger" OFF)
	option(USE_PHYSX "Use physx" OFF)
	option(USE_JS_V8 "Use v8" OFF)
	option(USE_JS_OHOS_JSVM "Use ohos jsvm api" ON)
	option(CONCH_USE_JPEG_XL "USE JPEG XL" ON)
	find_library(EGL-lib EGL)
	find_library(GLESv3-lib GLESv3)
	find_library(hilog-lib hilog_ndk.z)
	find_library(libace-lib ace_ndk.z)
	find_library(libnapi-lib ace_napi.z)
	find_library(libuv-lib uv)
	find_library(rawfile-lib rawfile.z)
	find_library(Drawing-lib native_drawing)
	add_definitions(-fexceptions)
	#add_definitions(-DIN_LIBRARY)
	#add_definitions(-D_GLIBCXX_PERMIT_BACKWARD_HASH)
	add_definitions(-DOHOS_ARM_NEON=TRUE)
	add_definitions(-DOHOS_STL=c++_shared)
	add_definitions(-DOHOS_TOOLCHAIN=clang)
	add_definitions(-fno-rtti)
	add_definitions(-DAL_ALEXT_PROTOTYPES)
elseif(OS_LINUX)
	option(CONCH_USE_OLD_CURL_DOWNLOAD "Use CURL" ON)
	option(USE_JS_V8_DEBUGGER "Use v8 debugger" ON)
	option(CONCH_USE_JPEG_XL "USE JPEG XL" OFF)
	option(USE_PHYSX "Use physx" OFF)
	option(USE_JS_V8 "Use v8" ON)
endif()

if(CONCH_USE_SWAPPY)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_SWAPPY")
endif()
if(USE_JS_V8_DEBUGGER)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DJS_V8_DEBUGGER")
endif()
if(USE_JS_V8)
	add_definitions(-DJS_V8)
endif()
if(CONCH_USE_JPEG_XL)
	add_definitions(-DJPEG_XL)
endif()
if(USE_JS_OHOS_JSVM)
	add_definitions(-DJS_OHOS_JSVM)
endif()
if(CONCH_USE_CURL_DOWNLOAD)
	add_definitions(-DCURL_DOWNLOAD)
endif()
if(CONCH_USE_OLD_CURL_DOWNLOAD)
	add_definitions(-DCURL_OLD_DOWNLOAD)
endif()
if(CONCH_USE_DCC)
	add_definitions(-DUSE_DCC)
endif()
if(TRACY_PROFILER_ENABLED)
	add_definitions(-DTRACY_PROFILER_ENABLED)
endif()
if(USE_PHYSX)
	add_definitions(-DPHYSX)
endif()
if(OS_WINDOWS)
 	add_compile_definitions(UNICODE _UNICODE)
	set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT launcher)
	# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W0 /Zc:__cplusplus")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG /std:c++17")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG /std:c++17")
	file(GLOB WIN_DLLS 
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/v8/lib/win64/*.dll 
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/angle/lib/win64/*.dll
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/openal/lib/win64/*.dll
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/ffmpeg/bin/win64/*.dll
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/jxl/lib/win64/*.dll
		${CMAKE_CURRENT_SOURCE_DIR}/third_party/sqlite/lib/win64/*.dll
	)
else()
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -std=c++17")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG -std=c++17")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -std=c++17")
endif()

if(OS_ANDROID)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
endif()

if(OS_LINUX)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
endif()

if(OS_LINUX)
else()
# 设置可执行文件的输出目录
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
endif()
if(BUILDING_CONCH_SHARED )
   add_definitions(-DBUILDING_CONCH_SHARED)
endif()
if(NOT BUILDING_CONCH_SHARED AND NOT BUILDING_CONCH_STATIC)
   if(OS_LINUX OR OS_IOS OR OS_WINDOWS)
		add_subdirectory(template)
   endif()
endif()

add_subdirectory(modules/utils)
add_subdirectory(modules/jsbind)
add_subdirectory(modules/jsvm)
add_subdirectory(modules/core)
add_subdirectory(modules/webstorage)
add_subdirectory(modules/profiler profiler)
add_subdirectory(modules/crypto-core crypto-core)
if(OS_WINDOWS)
add_subdirectory(modules/video)
endif()
if(CONCH_USE_CURL_DOWNLOAD)
add_subdirectory(modules/network)
endif()
add_subdirectory(conch)


if(USE_PHYSX)
add_subdirectory(third_party/physx physx)
endif()
if(OS_WINDOWS)
add_subdirectory(third_party/ffmpeg ffmpeg)
endif()
if(CONCH_USE_JPEG_XL)
add_subdirectory(third_party/jxl jxl)
endif()
add_subdirectory(third_party/iniparser iniparser)
add_subdirectory(third_party/zlib zlib)
add_subdirectory(third_party/zip zip)
add_subdirectory(third_party/websockets websockets)
add_subdirectory(third_party/openssl openssl)
add_subdirectory(third_party/png png)
add_subdirectory(third_party/rapidxml rapidxml)
add_subdirectory(third_party/ghc ghc)
add_subdirectory(third_party/jpeg-turbo jpeg-turbo)
if(NOT OS_LINUX)
add_subdirectory(third_party/mpg123 mpg123)
endif()
if(OS_OHOS)
add_subdirectory(third_party/aki aki_jsbind)
endif()
if(NOT OS_IOS)
add_subdirectory(third_party/sqlite sqlite)
endif()
add_subdirectory(third_party/openal openal)
add_subdirectory(third_party/ogg ogg)
add_subdirectory(third_party/freetype freetype)
add_subdirectory(third_party/curl curl)
if(OS_OHOS)
add_subdirectory(third_party/v8_9.1 v8)
else()
add_subdirectory(third_party/v8 v8)
endif()
add_subdirectory(third_party/angle angle)
add_subdirectory(third_party/bullet bullet)
add_subdirectory(third_party/sdl sdl)
add_subdirectory(third_party/benchmark benchmark)
if(TRACY_PROFILER_ENABLED)
	add_subdirectory(third_party/tracy tracy)
endif()	
if(CONCH_USE_SWAPPY)
	add_subdirectory(third_party/swappy swappy)
endif()


message("CMAKE_BUILD_TYPE:${CMAKE_BUILD_TYPE}")
message("CMAKE_C_FLAGS:${CMAKE_C_FLAGS}")
message("CMAKE_CXX_FLAGS:${CMAKE_CXX_FLAGS}")
message("CMAKE_C_FLAGS_RELEASE:${CMAKE_C_FLAGS_RELEASE}")
message("CMAKE_CXX_FLAGS_RELEASE:${CMAKE_CXX_FLAGS_RELEASE}")
message("CMAKE_C_FLAGS_DEBUG:${CMAKE_C_FLAGS_DEBUG}")
message("CMAKE_CXX_FLAGS_DEBUG:${CMAKE_CXX_FLAGS_DEBUG}")
