#ifndef __Shader3D_H__
#define __Shader3D_H__

#include <stdio.h>
#include <vector>

namespace laya
{
	enum class Shader3D
	{
		RENDER_STATE_CULL = 0,
		RENDER_STATE_BLEND = 1,
		RENDER_STATE_BLEND_SRC = 2,
		RENDER_STATE_BLEND_DST = 3,
		RENDER_STATE_BLEND_SRC_RGB = 4,
		RENDER_STATE_BLEND_DST_RGB = 5,
		RENDER_STATE_BLEND_SRC_ALPHA = 6,
		RENDER_STATE_BLEND_DST_ALPHA = 7,
		RENDER_STATE_BLEND_CONST_COLOR = 8,
		RENDER_STATE_BLEND_EQUATION = 9,
		RENDER_STATE_BLEND_EQUATION_RGB = 10,
		RENDER_STATE_BLEND_EQUATION_ALPHA = 11,
		RENDER_STATE_DEPTH_TEST = 12,
		RENDER_STATE_DEPTH_WRITE = 13,
		RENDER_STATE_STENCIL_TEST = 14,
		RENDER_STATE_STENCIL_WRITE = 15,
		RENDER_STATE_STENCIL_REF = 16,
		RENDER_STATE_STENCIL_OP = 17,
	};
}
#endif //__Shader3D_H__
