add_definitions(-DCONCH)

if(NOT BUILDING_ARCH)
    set(BUILDING_ARCH "${CMAKE_HOST_SYSTEM_PROCESSOR}")

    if(CMAKE_OSX_ARCHITECTURES MATCHES ".*;.*")
        set(BUILDING_ARCH "universal")
    else()
        if(NOT "${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            set(BUILDING_ARCH "${CMAKE_OSX_ARCHITECTURES}")
        endif()
    endif()
endif()

string(TOLOWER "${BUILDING_ARCH}" BUILDING_ARCH)
string(REPLACE "amd64" "x64" BUILDING_ARCH "${BUILDING_ARCH}")

if(NOT DIST_DIR)
    set(DIST_DIR "${BUILDING_ARCH}")
endif()

if(OHOS)
    set(OS_OHOS TRUE)
    add_definitions(-DOS_OHOS=1)
    # set(CMAKE_CXX_FLAGS "-fvisibility=hidden -fvisibility-inlines-hidden ${CMAKE_CXX_FLAGS}")
    if("${OHOS_ARCH}" STREQUAL "armeabi-v7a")
        set(CMAKE_CXX_FLAGS "-march=armv7a ${CMAKE_CXX_FLAGS}")
    endif()
    message("OS OHOS")
elseif(ANDROID)
    set(OS_ANDROID TRUE)
    add_definitions(-DOS_ANDROID=1)
    message("OS ANDROID")
elseif(MSVC)
    set(OS_WINDOWS TRUE)
    add_definitions(-DOS_WINDOWS=1)
    message("OS WIN")
elseif(IOS)
    set(OS_IOS TRUE)
    add_definitions(-DOS_IOS=1)
    message("OS IOS")
elseif(LINUX)
    set(OS_LINUX TRUE)
    add_definitions(-DOS_LINUX=1)
    message("OS LINUX")
endif()